# Sports Analytics Basics

### Lesson Plan

* Python
* Pandas
* Numpy

In [1]:
# Import the necessary modules as aliases

import pandas as pd
import numpy as np
import numpy as np

### Pandas Basics

In [3]:
# Creating Series

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
# Creating DataFrames

df = pd.DataFrame(
    {
        "Basketball": 1.0,
        "Football": pd.Timestamp("20130102"),
        "Hockey": pd.Series(1, index=list(range(4)), dtype="float32"),
        "Soccer": np.array([3] * 4, dtype="int32"),
        "Bouldering": pd.Categorical(["test", "train", "test", "train"])
    }
)

In [6]:
df

   Basketball   Football  Hockey  Soccer Bouldering
0         1.0 2013-01-02     1.0       3       test
1         1.0 2013-01-02     1.0       3      train
2         1.0 2013-01-02     1.0       3       test
3         1.0 2013-01-02     1.0       3      train

In [16]:
# Retrieving data

url = 'https://raw.githubusercontent.com/UBC-MDS/DSCI_522_OlympicMedalPrediction/master/data/athlete_events.csv'
olympics = pd.read_csv(url)

In [10]:
# Observing entries

olympics.head(20)

# olympics.tail(20)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN

In [ ]:
# Indexing into Data
olympics.loc[olympics.Age == 19]
olympics.loc[olympics['Team'] == 'United States']
olympics.loc[olympics['Team'] == 'University of Toronto']

olympics.iloc[0:10]
olympics.iloc[-1:]

In [ ]:
# Sorting Values

olympics.sort_values(by='Year', ascending=True)
olympics.sort_values(by='Year', ascending=False)

In [ ]:
# Boolean Selection

olympics.loc[(olympics['Age'] == 19) & (olympics['Team'] == 'Canada') & (olympics['Year'] == 2016)]
olympics.loc[(olympics['Age'] == 19) | (olympics['Team'] == 'Canada') | (olympics['Year'] == 2016)]

In [ ]:
olympics.columns

In [ ]:
# Removing Columns

olympics.drop(columns='ID')

In [ ]:
olympics

In [ ]:
olympics.drop(columns='ID', inplace=True)
olympics

In [ ]:
# Cleaning Data

olympics.fillna(0)

In [ ]:
olympics['Medal'].fillna(0, inplace=True)

In [ ]:
# Removing Rows

olympics.dropna(inplace=True)

In [ ]:
# Descriptive Statistics

olympics[['Height', 'Weight']].describe()

In [ ]:
# Value Counts
olympics['Medal'].value_counts()

In [ ]:
# Vectorized Operations

def convert_to_freedom_units(x):
    return x / 2.54


olympics['Height'] = olympics['Height'].apply(convert_to_freedom_units)
olympics

In [ ]:
# Merging / Joining

olympics_M = olympics[olympics['Sex']=='M']
olympics_F = olympics.loc[olympics['Sex'] == 'F']

olympics_M

In [ ]:
olympics_F

In [ ]:
pd.concat([olympics_M, olympics_F])

In [ ]:
# Observing
olympics.Team.unique()

olympics.Team.nunique()

In [ ]:
# Grouping Data

olympics.groupby(by='NOC')['Medal'].value_counts()

In [ ]:
# Converting to numpy

df.to_numpy()

In [ ]:
# Excel

olympics.to_csv('olympics.csv')